### ISSUE TITLE
Support MariaDB?

### ISSUE THREAD

**Issue by tatut** [tamizhvendan/honeyeql#12]
MariaDB should be the same as MySQL for most intents and purposes, but the JDBC product name differs.

I did a quick attempt in the REPL, and if I hack `honeyeql.meta-data/fetch` to override the "MariaDB" db-product-name with "MySQL" it does look like the adapter is intialized correctly (entity meta-data looks correct).

But I can't seem to get any results, the result is empty (adding a `tap>` listener to trace the SQL, the query looks correct). Perhaps some other place requires changes as well?

**Comment by tatut** [comment]
Ah, I see nested pulls are using `LATERAL` which is not supported in MariaDB 10.x... so I guess this isn't as straight forward as I initially thought.

**Comment by tamizhvendan** [comment]
Closing this as I don't have any plans for supporting MariaDB anytime soon. PRs are welcome :)
